name: Scan Template

on:
  workflow_call:
    inputs:
      PRODUCT_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      userKey:
        required: true

jobs:
  scan:
    runs-on: [self-hosted, windows]
    env:
      userKey: ${{ secrets.userKey }}
      productName: ${{ inputs.PRODUCT_NAME }}
      projectName: ${{ inputs.PROJECT_NAME }}

    steps:
      - name: 確認環境變數
        run: |
          echo userKey = %userKey%
          echo productName = %productName%
          echo projectName = %projectName%
        shell: cmd

      - name: 執行掃描腳本
        run: |
          echo 開始執行 Mend 掃描...
          C:\WS-OnlineScan\Scan.bat
        shell: cmd
